#!/bin/bash
clear
echo
echo "                                   DOKUMENTASI                                "
echo "   __   __  ______   _______  ___      ___   _______         _______  __   __ "
echo "  |  |_|  ||      | |   _   ||   |    |   | |   _   |       |       ||  | |  |"
echo "  |       ||  _    ||  |_|  ||   |    |   | |  |_|  |       |  _____||  |_|  |"
echo "  |       || |_|   ||  |_|  ||   |    |   | |  |_|  |       | |_____ |       |"
echo "  |       || |_|   ||       ||   |___ |   | |       |       |_____  ||       |"
echo "  | ||_|| ||       ||   _   ||       ||   | |   _   |   _    _____| ||   _   |"
echo "  |_|   |_||______| |__| |__||_______||___| |__| |__|  |_|  |_______||__| |__|"
echo "   ____   ____   ___________   ____   ____   ____   ___________   ____   ____ "
echo "  |____| |____| |___________| |____| |____| |____| |___________| |____| |____|";echo;echo
echo "susu = sudo su"
echo "susu"
echo ""
echo "pasang = sudo apt-get install"
echo "pasang firefox"
echo ""
echo "pasangk(pasang kekurangan) = sudo apt-get -f install"
echo "pasangk"
echo ""
echo "pasangu(pasang ulang) = sudo apt-get install --reinstall"
echo "pasangu firefox"
echo ""
echo "bongkar = sudo apt-get remove"
echo "bongkar firefox"
echo ""
echo "perbarui = sudo apt-get update"
echo "memperbarui repository"
echo ""
echo "tingkatkan = sudo apt-get upgrade"
echo "tingkatkan firefox"
echo ""
echo "tingkatkand(tingkatkan distribusi) = sudo apt-get dist-upgrade"
echo "tingkatkand"
echo ""
echo "tambah-repo = sudo add-apt-repository"
echo "tambah-repo ppa:nilarimogard/webupd8"
echo ""
echo "hapus-repo = sudo add-apt-repository --remove"
echo "hapus repo ppa:nilarimogard/webupd8"
echo ""
echo "sunting-repo = sudo nano /etc/apt/sources.list"
echo "sunting-repo"
echo ""
echo "rekonfig(merekonfigurasi ulang) = sudo dpkg-reconfigure"
echo "rekonfig firefox"
echo ""
echo "salin = cp"
echo "salin teks1.txt teks2.txt"
echo ""
echo "pindah = mv"
echo "pindah teks1.txt dokumenku/"
echo ""
echo "pindah(merubah nama) = mv"
echo "pindah teks1.txt teks2.txt (merubah nama teks1 menjadi teks2)"
echo " "
echo "buat = touch"
echo "buat teks1.txt"
echo ""
echo "buatdir(direktori) = mkdir"
echo "buatdir folderku"
echo ""
echo "hapus = rm"
echo "hapus teks1.txt"
echo ""
echo "hapusdir(direktori) = rmdir"
echo "hapusdir folderku"
echo ""
echo "lihat = cat"
echo "lihat teks1.txt"
echo ""
echo "daftar = ls"
echo "ls"
echo ""
echo "tulis = cat >"
echo "tulis teks1.txt"
echo ""
echo "sunting = cat >>"
echo "sunting teks1.txt"
echo ""
echo "unduh = wget"
echo "unduh google.com/image.jpeg"
echo ""
echo "ke = cd"
echo "ke folderku"
echo ""
echo "kembali = cd .."
echo "kembali"
echo ""
echo "kembalike (home/dir1 = home/dir2) = cd .. ; cd"
echo "kembalike dir2"
echo ""
echo "keluar = exit"
echo "x = exit"
echo ""
echo ". = cd .."
echo ".. = cd ../.."
echo "... = cd ../../.."
echo ""
echo "untar = tar -zxvf"
echo "untar mdaliash.tar.gz"
echo ""
echo "hentikan = killall"
echo "killall firefox"
echo ""
echo "pasangl(luring) = sudo dpkg -i"
echo "pasangl = sudo dpkg -i otodidak.deb"
echo ""
echo "pasangls(luring semua) = sudo dpkg -i *.deb"
echo "pasangls libreoffice/*.deb"
echo ""
echo "tanggal = date"
echo "tanggal"
echo ""
echo "kalender = cal"
echo "kalender"
echo ""
echo "sandi (ubah sandi) = passwd"
echo "passwd"
echo ""
echo "lupa (permission denied)= sudo !!"
echo "lupa"
echo ""
echo "bersihkan (terminal) = clear"
echo "clear"
echo ""
echo "riwayat = history"
echo "riwayat"
echo ""
echo "matikan = sudo shutdown -h now"
echo "matikan"
echo ""
echo "nyalakan (ulang) = sudo shutdown -r now"
echo "nyalakan"
echo ""
echo "jjar = java -jar"
echo "jjar Minecraft.jar"
echo ""
echo "py = python"
echo "py"
echo
echo "Kamu juga bisa menyunting ini di ~/.bash_aliases"
echo "Atau juga di menu mdaliash 3.Penyuntingan"
